// Generated by `npm run sync-idl` from protocol/target. Do not edit.

/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/zero_policy.json`.
 */
export type ZeroPolicy = {
  "address": "EK8aHDV1rgmoi7aygKCptretPMwQ9b6U293dioDLGZYW",
  "metadata": {
    "name": "zeroPolicy",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Created with Anchor"
  },
  "instructions": [
    {
      "name": "addProvider",
      "discriminator": [
        16,
        145,
        244,
        119,
        24,
        192,
        154,
        71
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "provider",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "closePolicy",
      "discriminator": [
        55,
        42,
        248,
        229,
        222,
        138,
        26,
        252
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy",
          "writable": true
        },
        {
          "name": "mint",
          "relations": [
            "policy"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "policy"
              }
            ]
          }
        },
        {
          "name": "destination",
          "writable": true
        },
        {
          "name": "tokenProgram"
        }
      ],
      "args": []
    },
    {
      "name": "createPolicy",
      "discriminator": [
        27,
        81,
        33,
        27,
        196,
        103,
        246,
        53
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "policy",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  111,
                  108,
                  105,
                  99,
                  121
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "arg",
                "path": "spender"
              }
            ]
          }
        },
        {
          "name": "mint"
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "policy"
              }
            ]
          }
        },
        {
          "name": "tokenProgram"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "spender",
          "type": "pubkey"
        },
        {
          "name": "maxPerPayment",
          "type": "u64"
        },
        {
          "name": "dailyLimit",
          "type": "u64"
        },
        {
          "name": "allowlist",
          "type": {
            "vec": "pubkey"
          }
        }
      ]
    },
    {
      "name": "deposit",
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy"
        },
        {
          "name": "mint",
          "relations": [
            "policy"
          ]
        },
        {
          "name": "ownerTokenAccount",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "policy"
              }
            ]
          }
        },
        {
          "name": "tokenProgram"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "pay",
      "discriminator": [
        119,
        18,
        216,
        65,
        192,
        117,
        122,
        220
      ],
      "accounts": [
        {
          "name": "spender",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy",
          "writable": true
        },
        {
          "name": "mint",
          "relations": [
            "policy"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "policy"
              }
            ]
          }
        },
        {
          "name": "recipient",
          "docs": [
            "Token account of the provider being paid. Its owner must be allowlisted."
          ],
          "writable": true
        },
        {
          "name": "tokenProgram"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "removeProvider",
      "discriminator": [
        100,
        1,
        225,
        45,
        96,
        44,
        30,
        13
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "provider",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "setPaused",
      "discriminator": [
        91,
        60,
        125,
        192,
        176,
        225,
        166,
        218
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "updateLimits",
      "discriminator": [
        89,
        37,
        137,
        60,
        75,
        70,
        48,
        194
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "maxPerPayment",
          "type": "u64"
        },
        {
          "name": "dailyLimit",
          "type": "u64"
        }
      ]
    },
    {
      "name": "withdraw",
      "discriminator": [
        183,
        18,
        70,
        156,
        148,
        109,
        161,
        34
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "policy"
          ]
        },
        {
          "name": "policy"
        },
        {
          "name": "mint",
          "relations": [
            "policy"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "policy"
              }
            ]
          }
        },
        {
          "name": "destination",
          "writable": true
        },
        {
          "name": "tokenProgram"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "policy",
      "discriminator": [
        222,
        135,
        7,
        163,
        235,
        177,
        33,
        68
      ]
    }
  ],
  "events": [
    {
      "name": "deposited",
      "discriminator": [
        111,
        141,
        26,
        45,
        161,
        35,
        100,
        57
      ]
    },
    {
      "name": "limitsUpdated",
      "discriminator": [
        160,
        131,
        108,
        76,
        91,
        80,
        118,
        137
      ]
    },
    {
      "name": "pauseChanged",
      "discriminator": [
        238,
        188,
        213,
        78,
        134,
        209,
        178,
        218
      ]
    },
    {
      "name": "paymentSettled",
      "discriminator": [
        158,
        182,
        152,
        76,
        105,
        23,
        232,
        135
      ]
    },
    {
      "name": "policyClosed",
      "discriminator": [
        19,
        126,
        82,
        173,
        79,
        86,
        50,
        51
      ]
    },
    {
      "name": "policyCreated",
      "discriminator": [
        59,
        189,
        65,
        121,
        86,
        157,
        108,
        10
      ]
    },
    {
      "name": "providerAdded",
      "discriminator": [
        206,
        144,
        232,
        247,
        30,
        115,
        117,
        45
      ]
    },
    {
      "name": "providerRemoved",
      "discriminator": [
        192,
        1,
        155,
        196,
        113,
        29,
        126,
        25
      ]
    },
    {
      "name": "withdrawn",
      "discriminator": [
        20,
        89,
        223,
        198,
        194,
        124,
        219,
        13
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "paused",
      "msg": "Policy is paused"
    },
    {
      "code": 6001,
      "name": "recipientNotAllowed",
      "msg": "Recipient is not on the policy allowlist"
    },
    {
      "code": 6002,
      "name": "amountExceedsMaxPayment",
      "msg": "Amount exceeds the policy's max payment"
    },
    {
      "code": 6003,
      "name": "dailyLimitExceeded",
      "msg": "Payment would exceed the policy's daily limit"
    },
    {
      "code": 6004,
      "name": "zeroAmount",
      "msg": "Amount must be greater than zero"
    },
    {
      "code": 6005,
      "name": "allowlistFull",
      "msg": "Allowlist is full"
    },
    {
      "code": 6006,
      "name": "duplicateProvider",
      "msg": "Provider is already on the allowlist"
    },
    {
      "code": 6007,
      "name": "unauthorized",
      "msg": "Signer is not authorized for this policy"
    },
    {
      "code": 6008,
      "name": "mathOverflow",
      "msg": "Arithmetic overflow"
    },
    {
      "code": 6009,
      "name": "providerNotFound",
      "msg": "Provider is not on the allowlist"
    },
    {
      "code": 6010,
      "name": "invalidLimits",
      "msg": "Limits must be non-zero and max_per_payment must not exceed daily_limit"
    },
    {
      "code": 6011,
      "name": "unsupportedMint",
      "msg": "Mint uses a Token-2022 extension this program does not support"
    }
  ],
  "types": [
    {
      "name": "deposited",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "source",
            "docs": [
              "Owner token account the tokens came from."
            ],
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "limitsUpdated",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "maxPerPayment",
            "type": "u64"
          },
          {
            "name": "dailyLimit",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "pauseChanged",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "paused",
            "type": "bool"
          }
        ]
      }
    },
    {
      "name": "paymentSettled",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "spender",
            "type": "pubkey"
          },
          {
            "name": "mint",
            "type": "pubkey"
          },
          {
            "name": "recipient",
            "docs": [
              "Provider wallet (owner of the recipient token account)."
            ],
            "type": "pubkey"
          },
          {
            "name": "recipientTokenAccount",
            "docs": [
              "Token account that received the payment."
            ],
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "spentInWindow",
            "docs": [
              "Total paid across the last 24 hourly buckets, including this payment."
            ],
            "type": "u64"
          },
          {
            "name": "dailyLimit",
            "type": "u64"
          },
          {
            "name": "timestamp",
            "docs": [
              "Cluster unix time of the payment."
            ],
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "policy",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "version",
            "docs": [
              "Layout version (`POLICY_VERSION`)."
            ],
            "type": "u8"
          },
          {
            "name": "owner",
            "docs": [
              "Wallet that created the policy; controls limits, allowlist, pause and withdrawals."
            ],
            "type": "pubkey"
          },
          {
            "name": "spender",
            "docs": [
              "Key allowed to request payments."
            ],
            "type": "pubkey"
          },
          {
            "name": "mint",
            "type": "pubkey"
          },
          {
            "name": "maxPerPayment",
            "docs": [
              "Largest single payment, in base units of `mint`."
            ],
            "type": "u64"
          },
          {
            "name": "dailyLimit",
            "docs": [
              "Most that can be spent across the last `WINDOW_BUCKETS` hourly buckets, in base units."
            ],
            "type": "u64"
          },
          {
            "name": "buckets",
            "docs": [
              "Amount paid in each hour, indexed by `hour % WINDOW_BUCKETS`, where",
              "`hour = unix_timestamp / BUCKET_SECONDS`. Only buckets for the 24 hours up to and",
              "including `last_hour` are meaningful; older ones are cleared lazily on the next payment."
            ],
            "type": {
              "array": [
                "u64",
                24
              ]
            }
          },
          {
            "name": "lastHour",
            "docs": [
              "Hour (`unix_timestamp / BUCKET_SECONDS`) of the most recent payment; 0 before the first."
            ],
            "type": "i64"
          },
          {
            "name": "allowlist",
            "docs": [
              "Provider wallets allowed to receive payments. Only the first `allowlist_count` are valid."
            ],
            "type": {
              "array": [
                "pubkey",
                8
              ]
            }
          },
          {
            "name": "allowlistCount",
            "type": "u8"
          },
          {
            "name": "paused",
            "type": "bool"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "reserved",
            "docs": [
              "Reserved for future fields; always zero in version 1."
            ],
            "type": {
              "array": [
                "u8",
                64
              ]
            }
          }
        ]
      }
    },
    {
      "name": "policyClosed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "destination",
            "docs": [
              "Token account that received the swept vault balance."
            ],
            "type": "pubkey"
          },
          {
            "name": "swept",
            "docs": [
              "Vault balance swept to `destination` (may be 0)."
            ],
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "policyCreated",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "spender",
            "type": "pubkey"
          },
          {
            "name": "mint",
            "type": "pubkey"
          },
          {
            "name": "maxPerPayment",
            "type": "u64"
          },
          {
            "name": "dailyLimit",
            "type": "u64"
          },
          {
            "name": "allowlist",
            "type": {
              "vec": "pubkey"
            }
          }
        ]
      }
    },
    {
      "name": "providerAdded",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "provider",
            "type": "pubkey"
          }
        ]
      }
    },
    {
      "name": "providerRemoved",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "provider",
            "type": "pubkey"
          }
        ]
      }
    },
    {
      "name": "withdrawn",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "policy",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "destination",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          }
        ]
      }
    }
  ],
  "constants": [
    {
      "name": "bucketSeconds",
      "docs": [
        "Width of one spending bucket, in seconds (one hour)."
      ],
      "type": "i64",
      "value": "3600"
    },
    {
      "name": "policySeed",
      "type": "bytes",
      "value": "[112, 111, 108, 105, 99, 121]"
    },
    {
      "name": "policyVersion",
      "docs": [
        "Layout version of the `Policy` account."
      ],
      "type": "u8",
      "value": "1"
    },
    {
      "name": "vaultSeed",
      "type": "bytes",
      "value": "[118, 97, 117, 108, 116]"
    },
    {
      "name": "windowBuckets",
      "docs": [
        "Number of hourly buckets in the spending window. The daily limit applies to the sum of the",
        "current hour's bucket and the 23 before it, so a payment counts against the limit until the",
        "24th hour boundary after it: for at least 23 and at most 24 hours."
      ],
      "type": "u8",
      "value": "24"
    }
  ]
};
