// Copies the IDL and its TypeScript type from protocol/ (after `npm run build` there) into
// src/idl/, so the SDK builds without an Anchor toolchain. Run it whenever the program changes.
//
//   node scripts/sync-idl.mjs           write src/idl/
//   node scripts/sync-idl.mjs --check   exit 1 if src/idl/ differs from protocol/target/
//                                       (skipped, exit 0, if protocol/ hasn't been built)
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const protocol = new URL("../../protocol/target/", import.meta.url);
const out = new URL("../src/idl/", import.meta.url);
const header = "// Generated by `npm run sync-idl` from protocol/target. Do not edit.\n";
const idlSource = new URL("idl/xero_policy.json", protocol);
const typesSource = new URL("types/xero_policy.ts", protocol);
const check = process.argv.includes("--check");

if (!existsSync(idlSource) || !existsSync(typesSource)) {
  const message = `protocol/target/{idl,types} not found; run \`npm run build\` in protocol/ first`;
  if (check) {
    console.warn(`sync-idl --check skipped: ${message}`);
    process.exit(0);
  }
  console.error(message);
  process.exit(1);
}

const idl = JSON.parse(readFileSync(idlSource, "utf8"));
const generated = {
  "idl.ts": `${header}\n/** The xero_policy IDL as emitted by Anchor (snake_case). */\nexport const IDL = ${JSON.stringify(idl, null, 2)};\n`,
  "xero_policy.ts": `${header}\n${readFileSync(typesSource, "utf8")}`,
};

if (check) {
  const stale = Object.entries(generated).filter(([file, content]) => {
    const target = new URL(file, out);
    return !existsSync(target) || readFileSync(target, "utf8") !== content;
  });
  if (stale.length) {
    console.error(
      `src/idl is out of sync with protocol/target (${stale.map(([f]) => f).join(", ")}); ` +
        "run `npm run sync-idl`",
    );
    process.exit(1);
  }
  console.log(`src/idl matches protocol/target (program ${idl.address})`);
} else {
  for (const [file, content] of Object.entries(generated))
    writeFileSync(new URL(file, out), content);
  console.log(`synced IDL for program ${idl.address}`);
}
